CREATE INDEX IDX_CRED_ROLES_CREDENTIAL_ID ON CREDENTIALS_ROLES(CREDENTIAL_ID);
CREATE INDEX IDX_CREDENTIAL_TENANT_ID ON IOT_CREDENTIAL(TENANT_ID); 
CREATE INDEX IDX_GEOFENCES_PD_ID ON IOT_GEOFENCES(PROJECT_ID, DEVICE_ID); 
CREATE INDEX IDX_SI_ORDER_ID ON IOT_ORDER_INSTANCE(ORDER_ID); 